### ISSUE TITLE
[BUG] Cannot read private Paratranz project

### ISSUE THREAD

**Issue by NicolasGrosjean** [Jeydolen/ParantranzHelper#1]
When testing the script on a  Paratranz project with private as privacy status, there is the following error

```
ParantranzHelper/helper.js:242
        print("Project selected: " + project.id + " " + project.name);
                                             ^

TypeError: Cannot read properties of undefined (reading 'id')
    at initApp (ParantranzHelper/helper.js:242:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This bug is minor, in fact the main use case of the script is to contribute to public projects.

**Comment by Jeydolen** [comment]
I added a proper way to cycle through all projects available to the user and a proper status handling.

This should be fixed
